CREATE TABLE IF NOT EXISTS admin_qa_sessions (
  id VARCHAR(191) PRIMARY KEY,
  user_id VARCHAR(191) NOT NULL DEFAULT 'admin',
  surface VARCHAR(32) NOT NULL DEFAULT 'admin',
  title VARCHAR(255) NOT NULL DEFAULT '新建问答',
  title_source VARCHAR(32) NOT NULL DEFAULT 'system',
  preview TEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  recording_ids JSON NOT NULL,
  scope_json JSON NOT NULL,
  model VARCHAR(255) NOT NULL DEFAULT '',
  prompt_version VARCHAR(64) NOT NULL DEFAULT '',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  archived_at DATETIME(6) NULL,
  deleted_at DATETIME(6) NULL,
  INDEX idx_admin_sessions_status (surface, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_qa_messages (
  id VARCHAR(191) PRIMARY KEY,
  recording_id VARCHAR(191) NULL,
  recording_ids JSON NOT NULL,
  user_id VARCHAR(191) NOT NULL DEFAULT 'admin',
  surface VARCHAR(32) NOT NULL DEFAULT 'admin',
  session_id VARCHAR(191) NOT NULL,
  question LONGTEXT NOT NULL,
  answer LONGTEXT NOT NULL,
  jump_to_ms BIGINT NOT NULL DEFAULT 0,
  citations JSON NOT NULL,
  attachments JSON NOT NULL,
  warning_text TEXT NOT NULL,
  empty_reason VARCHAR(255) NOT NULL DEFAULT '',
  scope_key VARCHAR(255) NOT NULL DEFAULT '',
  scope_label VARCHAR(500) NOT NULL DEFAULT '',
  scope_terms JSON NOT NULL,
  context_recording_ids JSON NOT NULL,
  favorite TINYINT UNSIGNED NOT NULL DEFAULT 0,
  deleted_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX idx_admin_messages_session (session_id, created_at),
  INDEX idx_admin_messages_deleted (deleted_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
